version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: "main"
    ignore:
      - dependency-name: "torch"
      - dependency-name: "lightning"
      - dependency-name: "comet-ml"
    commit-message:
      prefix: "[deps]"
      include: "scope"
