repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.13.0"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --preview]
      - id: ruff-format

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ["-d", "{extends: relaxed, rules: {line-length: disable}}"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
