repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.8.0"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ["-d", "{extends: relaxed, rules: {line-length: disable}}"]
