name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Step 2: Set up Pixi
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.48.1
          cache: true
          locked: true
      # Step 3: Ensure python is installed
      - name: Test Pixi
        run: pixi run python --version
      # Step 4: Download external data
      - name: Set up kaggle API
        run: |
          mkdir -p ~/.config/kaggle
          echo "${{ secrets.KAGGLE_API_TOKEN }}" > ~/.config/kaggle/kaggle.json
          chmod 600 ~/.config/kaggle/kaggle.json
      - name: Download trackml data
        run: pixi run python data/trackml/get_trackml_data.py
      # Step 5: Run tests
      - name: Run pytest defined in pyproject.toml
        run: pixi run test-ci
