name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.8.0"

      #- name: Run pyright
      #  run: uv run pyright
