name: Test
on: [push, pull_request]

# Define common steps as anchors
.common-setup: &common-setup
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup Pixi
    uses: prefix-dev/setup-pixi@v0.8.14
    with:
      pixi-version: v0.50.2
      cache: true
      locked: true
      environments: ci

  - name: Test pixi
    run: |
      pixi run -e ci python --version

  - name: Install Git LFS
    run: |
      git lfs install
      git lfs pull

.common-upload: &common-upload
  name: Upload test coverage to Codecov
  uses: codecov/codecov-action@v5
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - *common-setup
      - name: Run unit tests
        run: pixi run -e ci test-unit-ci
      - <<: *common-upload
        with:
          fail_ci_if_error: false
          file: ./coverage.xml
          flags: unit

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - *common-setup
      - name: Run integration tests
        run: pixi run -e ci test-integration-ci
      - <<: *common-upload
        with:
          fail_ci_if_error: false
          file: ./coverage.xml
          flags: integration
